version: "2"
linters:
  enable:
    - asasalint
    - bidichk
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - errchkjson
    - errorlint
    - exhaustive
    - ginkgolinter
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - wsl
  settings:
    staticcheck:
      checks:
        - all
        - -QF1008
        - -QF1001
    lll:
      line-length: 130
      tab-width: 4
    errcheck:
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - fmt.Fprintf
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-occurrences: 5
    godox:
      keywords:
        - FIXME
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - golines
    - goimports
  settings:
    golines:
      max-len: 130
      tab-len: 4
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
