linters:
  enable:
    - asasalint
    - bidichk
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - forbidigo
    - gci
    - ginkgolinter
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - gosimple
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testifylint
    - thelper
    - usestdlibvars
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
    - mnd
linters-settings:
  godox:
    keywords:
      - FIXME # FIXME generates a linter warning
  goconst:
    min-occurrences: 5
  tagliatelle:
    # check the struck tag name case
    case:
      rules:
        json: snake
        yaml: snake
  exhaustive:
    default-signifies-exhaustive: true
  errcheck:
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
      - fmt.Fprintf
issues:
  exclude-use-default: false
